version: '3.7'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8050:8050
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgresql
    image: postgres:12.0-alpine
    #image: postgres:14.1-alpine
    env_file:
      - ./.env.db.dev
    expose:
      - 5437
    ports:
      - 5437:5437
    command: -p 5437
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: