# Generated by Django 4.0.1 on 2022-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCorrelationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID юзера')),
                ('x_data_type', models.CharField(max_length=512, verbose_name='Тип данных X')),
                ('y_data_type', models.CharField(max_length=512, verbose_name='Тип данных Y')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('p_value', models.FloatField(verbose_name='Коэффициент корреляции Пирсона')),
            ],
            options={
                'verbose_name': 'Данные корреляции',
                'verbose_name_plural': 'Данные корреляции',
            },
        ),
    ]
