# Generated by Django 4.0.1 on 2022-01-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlationdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercorrelationdata',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='ID юзера'),
        ),
    ]
